### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by shaanen** [felicitychou/ZoomEye#1]
I would like to call functions in this project from my own Python 3 scripts, but I see this project is written in Python 2. Any suggestions on how to work with this?

**Comment by shaanen** [comment]
Found out Python has a program called '2to3' which can do the job I guess.

**Comment by felicitychou** [comment]
OK, I will work for it.

**Comment by felicitychou** [comment]
@sjorsng I have updated my code to support python 3. You can try to use it.
